### ISSUE TITLE
typo in url

### ISSUE THREAD

**Issue by hobbsy** [mayfrost/guides#11]
Hi - the link for "Essential Launcher" under ANDROID APPS has a few extra characters on the end (leading to a 404)

https://clemensbartz.de/essential-launcher/%5D
should be:
https://clemensbartz.de/essential-launcher/

https://github.com/mayfrost/guides/blob/master/ALTERNATIVES.md#android-apps

Launcher: OpenLauncher (8,3 MB) -> Catapult (4,7 MB) -> Lawnchair (3,1 MB) -> Paper Launch (2,8 MB) -> Launch Time (2,5 MB) -> Silverfish (1,5 MB) -> T-UI (1,2 MB) -> Search Based Launcher (622 KB) -> KISS (431 KB) -> Emerald Launcher (172 KB) -> Hayai Launcher (106 KB) -> Fast (76 KB) -> Essential Launcher (26 KB)

**Comment by mayfrost** [comment]
Thanks for noticing, the changes have been submitted.
