### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by CoBE10** [mayfrost/guides#17]
On [Web Browser](https://github.com/mayfrost/guides/blob/master/BROWSER.md) page link to [Url leak](https://addons.mozilla.org/en-US/firefox/addon/no-resource-uri-leak/) and user agents  is broken because addons were removed from mozila addons page.

**Comment by mayfrost** [comment]
Linked to homepage to fix missing link.

**Comment by CoBE10** [comment]
User agent link are broken too.

**Comment by mayfrost** [comment]
Added the github for Random Agent Spoofer and an alternative page for User-Agent JS Fixer.

**Comment by CoBE10** [comment]
Solved
