### ISSUE TITLE
what's wrong with BSDs?

### ISSUE THREAD

**Issue by catastrop** [mayfrost/guides#23]
>Use GNU/Linux on your computers, preferably free from "systemd". PCLinuxOS is an easy first choice, Devuan is a better option. Stay away from something called BSD.

Why BSDs are bad?

**Comment by tiagotriques** [comment]
#3

**Comment by catastrop** [comment]
I didn't get the answer

**Comment by catastrop** [comment]
@mayfrost ¿??

**Comment by catastrop** [comment]
@mayfrost ¿??
