### ISSUE TITLE
Stream token project shut down

### ISSUE THREAD

**Issue by MateuszOkulus** [mayfrost/guides#5]
[Decentralized Networking](https://github.com/mayfrost/guides/blob/master/ALTERNATIVES.md#decentralized-networking) -> Monetary Incentives
Stream Token project shut down according to the official [page](https://streamtoken.net/)
It probably should be removed from the list.

**Comment by mayfrost** [comment]
Changing reference to the active Github repo.

**Comment by MateuszOkulus** [comment]
Closing because link has been fixed.
